### ISSUE TITLE
Detailed out the Issues

### ISSUE THREAD

**Issue by Kaperskyguru** [zico404/student-s-lodge-finder#2]
Please List out the Issues remaining to fix in the Website. Because am kinda confuse where to start coding.

**Comment by zico404** [comment]
Chat me up on whatsapp

**Comment by zico404** [comment]
Alright, let me do it here.
Firstly when a user logs in he should be taken to user dashboard, same for admin but the both use one

**Comment by zico404** [comment]
Then I'll handle the admin area while you continue with the user dashboard I was working on

**Comment by Kaperskyguru** [comment]
ok.... i will try it now... bt i need time to understand ur codes
